#!/bin/bash

# exit if fail
set -e

# update system
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt install bash-completion
sudo apt install fzf

# homebrew setup
if ! command -v brew &>/dev/null; then
  echo "Installing Homebrew..."
  NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"

brew update || echo "Homebrew update failed"

# dotfiles setup
echo "Setting dotfiles configuration..."
DOTFILES_DIR="$HOME/dotfiles"
cd "$DOTFILES_DIR"|| exit 1

export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"

ln -sf "$DOTFILES_DIR/nvim" "$XDG_CONFIG_HOME/nvim"
ln -sf "$DOTFILES_DIR/.bashrc " "$HOME/.bashrc"

# brew packages
echo "Installing Homebrew packages..."
brew install fd ripgrep pyenv npm awscli neovim
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

echo -e "\n\n"
echo -e "\033[1;32m╭────────────────────────────────────────────╮\033[0m"
echo -e "\033[1;32m│                                            │\033[0m"
echo -e "\033[1;32m│           Devpod setup complete!           │\033[0m"
echo -e "\033[1;32m│                                            │\033[0m"
echo -e "\033[1;32m│        SSH into the devpod container       │\033[0m"
echo -e "\033[1;32m│                                            │\033[0m"
echo -e "\033[1;32m│     Then run this file for system setup:   │\033[0m"
echo -e "\033[1;32m│                                            │\033[0m"
echo -e "\033[1;32m│     ~/dotfiles/scripts/setup-system.sh     │\033[0m"
echo -e "\033[1;32m│                                            │\033[0m"
echo -e "\033[1;32m╰────────────────────────────────────────────╯\033[0m"
echo -e "\n\n"
