#!/bin/bash

set -e

sudo apt-get update -y
sudo apt-get upgrade -y

# Homebrew 

if ! command -v brew &>/dev/null; then
  echo "Installing Homebrew"
  NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"

brew update || echo "Homebrew update failed"

# Dotfiles setup
DOTFILES_DIR="$HOME/dotfiles"
cd "$DOTFILES_DIR"|| exit 1

export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"

ln -sf "$DOTFILES_DIR/config.nvim" "$XDG_CONFIG_HOME/nvim"
ln -sf "$DOTFILES_DIR/zsh-config/.zshrc" "$HOME/.zshrc"

# Brew packages
brew install fd ripgrep pyenv npm awscli neovim

echo "SETUP COMPLETE!"
