#!/bin/bash

git submodule init
git submodule update

export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"

ln -sf "$PWD/config.nvim" "$XDG_CONFIG_HOME"/nvim

ln -sf "$PWD/zsh-config/.zshrc" "$HOME"/.zshrc

packages=(
	fd
	ripgrep
	pyenv
	npm
	awscli
)

for package in "${packages[@]}"; do
	echo "Installing $package..."
	/home/linuxbrew/.linuxbrew/bin/brew install "$package"
done

echo "All packages from the setup script have been installed."
